definitions:
  steps:
    - step: &shellcheck
        name: check scripts
        image: koalaman/shellcheck-alpine:stable
        script:
          - |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
    - step: &tfm_init
        name: init - lint - validate
        image: hashicorp/terraform:latest
        script:
          - |
            cd ./modules || exit
            for f in *; do
              if [ -d "$f" ]; then
                # cycle through each module dir and initialize
                cd "$f" || exit
                if ! terraform init -input=false -backend=false; then exit $?; fi
                cd ..
              fi
            done
          - |
            chmod +x scripts/*.sh
            source ./scripts/lint.sh
            source ./scripts/validate.sh
    - step: &bump
        name: bump module version
        image:
          name: 086282490297.dkr.ecr.eu-west-1.amazonaws.com/xops-cicd-python-alpine:latest
          aws:
            access-key: $ECR_AWS_ACCESS_KEY_XOPS_PULL
            secret-key: $ECR_AWS_SECRET_KEY_XOPS_PULL
        script:
          - set -o pipefail
          - |
            # Update version
            chmod +x scripts/bump.sh
            source ./scripts/bump.sh
pipelines:
  branches:
    feature/*:
      - step:
          <<: *shellcheck
      - step:
          <<: *tfm_init
    master:
      - step:
          <<: *bump
